// Products
export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST';
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS';
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL';

export const RESET_PRODUCTS_LIST = 'RESET_PRODUCTS_LIST';

// Product details
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const RESET_PRODUCT_DETAILS = 'RESET_PRODUCT_DETAILS';

// Cart
export const ADD_PRODUCT_TO_CART = 'ADD_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ALL_PRODUCTS_FROM_CART = 'REMOVE_ALL_PRODUCTS_FROM_CART';
